USE MASTER
go
DROP DATABASE IF EXISTS  BDZAPATOS 
go
create database BDZAPATOS
go
USE BDZAPATOS
go


CREATE TABLE PAIS(
ID_PAIS INT NOT NULL IDENTITY(1,1),
NOMBRE_PAIS  VARCHAR(30) UNIQUE
)
GO
CREATE TABLE IDENTIFICACION(
ID_IDENTIF INT NOT NULL IDENTITY(1,1),
NOMBRE_IDENTI  VARCHAR(30) UNIQUE,
DIGITOS INT NOT NULL
)
GO

CREATE TABLE CLIENTE (
	ID_CLI INT NOT NULL IDENTITY(1,1),
	ID_IDENTIF INT NOT NULL,
	INDENTIF_CLIE  VARCHAR(15)NOT NULL UNIQUE,
	NOMBRE_CLI VARCHAR(30),
	APEPAT_CLI VARCHAR(50),
	APEMAT_CLI VARCHAR(50),
	ID_PAIS INT NOT NULL
)
GO

CREATE TABLE MODELO(
ID_MODELO INT NOT NULL IDENTITY(1,1),
NOMBRE_MODELO VARCHAR(50) NOT NULL ,
)
GO
CREATE TABLE MARCA(
ID_MARCA INT NOT NULL IDENTITY(1,1),
NOMBRE_MARCA VARCHAR(50) NOT NULL ,
)

CREATE TABLE ZAPATO (
	ID_ZAPATO INT NOT NULL IDENTITY(1,1),
	CDO_ZAPATO CHAR(12),
	NOMBRE_ZAPATO VARCHAR(30),
	DESC_ZAPATO VARCHAR(100),
	COST_ZAPATO INT NOT NULL,
	EXISTENCIA INT NOT NULL,
	ID_MODELO INT NOT NULL,	
	ID_MARCA INT NOT NULL
)
GO


CREATE TABLE FACTURA	(
	ID_FACT INT NOT NULL IDENTITY(1,1),
	COD_FACT CHAR(12),
	FECHA_FACT DATE,
	TIPO_MOV_FACT VARCHAR(7) ,	
	DESC_FACT DECIMAL(10,2),
	IGV_FAC DECIMAL(10,2),
	TOTAL_FACT DECIMAL(10,2),
	ID_CLI INT NOT NULL
	)
GO
	

CREATE TABLE DT_FACTURA(
ID_FACT INT NOT NULL ,
ID_ZAPATO INT NOT NULL,
COSTO_DT_FACT DECIMAL(10,2),
CANT_DT_FACT INT NOT NULL,
)
GO


---AGRAGANDO LOS  LOS PRIMARY KEY

ALTER TABLE PAIS ADD CONSTRAINT PK_PAIS PRIMARY KEY(ID_PAIS)
ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (ID_CLI)
ALTER TABLE MARCA ADD CONSTRAINT PK_MARCA PRIMARY KEY (ID_MARCA)
ALTER TABLE IDENTIFICACION ADD CONSTRAINT PK_IDENTIFICACION PRIMARY KEY (ID_IDENTIF)
ALTER TABLE MODELO ADD CONSTRAINT PK_MODELO PRIMARY KEY (ID_MODELO)
ALTER TABLE ZAPATO ADD CONSTRAINT PK_ZAPATO PRIMARY KEY (ID_ZAPATO)
ALTER TABLE FACTURA ADD CONSTRAINT PK_FACTURA PRIMARY KEY (ID_FACT)
ALTER TABLE DT_FACTURA ADD CONSTRAINT PK_DT_FACTURA PRIMARY KEY (ID_FACT,ID_ZAPATO)

---AGREGANDO LOS FOREING KEY --
ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_PAIS FOREIGN KEY (ID_PAIS)
REFERENCES PAIS (ID_PAIS)

ALTER TABLE CLIENTE ADD CONSTRAINT FK_CLIENTE_IDENTIFICACION FOREIGN KEY (ID_IDENTIF)
REFERENCES IDENTIFICACION (ID_IDENTIF)

ALTER TABLE ZAPATO ADD CONSTRAINT FK_ZAPATO_MODELO FOREIGN KEY (ID_MODELO)
REFERENCES MODELO (ID_MODELO)

ALTER TABLE ZAPATO ADD CONSTRAINT FK_ZAPATO_MARCA FOREIGN KEY (ID_MARCA)
REFERENCES MARCA (ID_MARCA)

ALTER TABLE FACTURA ADD CONSTRAINT FK_FACTURA_CLIENTE FOREIGN KEY (ID_CLI)
REFERENCES CLIENTE (ID_CLI)


ALTER TABLE DT_FACTURA ADD CONSTRAINT FK_DT_FACTURA_F FOREIGN KEY (ID_FACT)
REFERENCES FACTURA (ID_FACT)

ALTER TABLE DT_FACTURA ADD CONSTRAINT FK_FACTURA_Z FOREIGN KEY (ID_ZAPATO)
REFERENCES ZAPATO (ID_ZAPATO)
---AGREGANDO ALGUNOS CONSTRAINT

ALTER TABLE FACTURA ADD CONSTRAINT CK_TIPO_MOV_FACT
CHECK(TIPO_MOV_FACT='ENTRADA' OR  TIPO_MOV_FACT='SALIDA');


 ---AGREGANDO DATOS


INSERT INTO PAIS VALUES ('PERU')
INSERT INTO PAIS VALUES ('VENEZUELA')
INSERT INTO PAIS VALUES ('COLOMBIA')
INSERT INTO PAIS VALUES ('ECUADOR')
INSERT INTO PAIS VALUES ('ARGENTINA')
GO
INSERT INTO MARCA VALUES ('ADIDAS')
INSERT INTO MARCA VALUES ('NIKE')
INSERT INTO MARCA VALUES ('CAT')
INSERT INTO MARCA VALUES ('JHON HOLDEN')

INSERT INTO MODELO VALUES ('ZAPATILLAS')
INSERT INTO MODELO VALUES ('MOCASIN')
INSERT INTO MODELO VALUES ('BAILARINA')
INSERT INTO MODELO VALUES ('DEPORTIVA')
INSERT INTO MODELO VALUES ('ZAPATOS DE BROGUE')
GO

INSERT INTO IDENTIFICACION VALUES ('DNI',8)
INSERT INTO IDENTIFICACION VALUES ('RUC',11)
INSERT INTO IDENTIFICACION VALUES ('RECIBOXHON',11)
INSERT INTO IDENTIFICACION VALUES ('PASAPORTE',8)
GO
INSERT INTO CLIENTE VALUES (1,'75373195','DAVID','MATOS','SALVADOR',1)
INSERT INTO CLIENTE VALUES (1,'78965464','JOSE','RUBEN','SAENZ',1)
INSERT INTO CLIENTE VALUES (1,'75378949','RUBEN','BLADES','HILDERICO',1)
INSERT INTO CLIENTE VALUES (1,'75477898','GRABRIEL','GARCIA','MARQUEZ',1)
INSERT INTO CLIENTE VALUES (1,'75311114','MARIO','VARGAZ','LLOSA',1)
GO

INSERT INTO ZAPATO VALUES ('ZAPATO000001','BOTAS PASCUAS','BOTAS PARA INVIERNO',100.00,10,2,1)
INSERT INTO ZAPATO VALUES ('ZAPATO000002','CHUCK ',' EL CLASICO QUE TODOS CONOCEMOS',269.90,10,1,2)
INSERT INTO ZAPATO VALUES ('ZAPATO000003','GOLF le FLEURS','ZAPATILLAS PARA INVIERNO',100.00,10,2,3)
INSERT INTO ZAPATO VALUES ('ZAPATO000004','Merrell Moab','zapatillas exclusivas',479.90,10,2,4)
INSERT INTO ZAPATO VALUES ('ZAPATO000005','Sala CT Fiery Coral ','LAS ZAPATILLAS DE SALA',600.00,10,2,1)
GO
INSERT INTO FACTURA VALUES ('FACTUR000001','2020-06-05','SALIDA',20.50,36,236.00,1)
INSERT INTO FACTURA VALUES ('FACTUR000002','2018-06-05','ENTRADA',0,360,2360.00,2)
INSERT INTO FACTURA VALUES ('FACTUR000003','2015-05-25','ENTRADA',0,162,1062.00,3)
INSERT INTO FACTURA VALUES ('FACTUR000004','2020-08-15','ENTRADA',0,810,5310.00,2)
INSERT INTO FACTURA VALUES ('FACTUR000005','2020-06-30','SALIDA',15.00,108,693.00,5)
INSERT INTO FACTURA VALUES ('FACTUR000006','2020-06-30','SALIDA',15.00,108,693.00,5)
GO
INSERT INTO DT_FACTURA VALUES (1,1,100.00,2)
INSERT INTO DT_FACTURA VALUES (2,2,200.00,10)
INSERT INTO DT_FACTURA VALUES (3,3,90.00,10)
INSERT INTO DT_FACTURA VALUES (4,4,450.00,10)
INSERT INTO DT_FACTURA VALUES (5,5,600.0,1)
INSERT INTO DT_FACTURA VALUES (6,5,600.0,1)
GO
