
--CONSULTAS
--1 : Consulta la facturación de un cliente en específico.
IF OBJECT_ID ('FACTURAXCLIENTE') IS NOT NULL  
    DROP FUNCTION FACTURAXCLIENTE;  
GO  
CREATE FUNCTION FACTURAXCLIENTE(@IDCLIENTE int)  
RETURNS TABLE   
AS   

RETURN(
SELECT * FROM FACTURA WHERE ID_CLI=@IDCLIENTE
);

SELECT * FROM FACTURAXCLIENTE(1)

--2 :Consulta la facturación de un producto en específico.


 IF OBJECT_ID ('FACTURAXPRODUCTO') IS NOT NULL  
    DROP FUNCTION FACTURAXPRODUCTO;  
GO  
CREATE FUNCTION FACTURAXPRODUCTO(@IDPRODUCTO int)  
RETURNS TABLE   
AS   

RETURN(
SELECT * FROM DT_FACTURA WHERE ID_ZAPATO=1
);

SELECT * FROM FACTURAXPRODUCTO(1)

--3: Consulta la facturación de un rango de fechas.

 IF OBJECT_ID ('FACTURAXFECHA') IS NOT NULL  
    DROP FUNCTION FACTURAXFECHA;  
GO  
CREATE FUNCTION FACTURAXFECHA(@FECHA DATE)  
RETURNS TABLE   
AS   

RETURN(
SELECT * FROM FACTURA  WHERE FECHA_FACT =@FECHA
);

SELECT * FROM FACTURAXFECHA('2020-06-30')

--4: De la facturación, consulta los clientes únicos 
--(es decir, se requiere el listado de los clientes que han comprado por lo menos una vez, 
--pero en el listado no se deben repetir los clientes)



IF OBJECT_ID ('SP_CLIENTES_UNICOS') IS NOT NULL
	DROP PROC SP_CLIENTES_UNICOS
GO
CREATE PROCEDURE SP_CLIENTES_UNICOS
AS
	SELECT ID_CLI,NOMBRE_CLI
	FROM CLIENTE
	WHERE EXISTS (SELECT ID_CLI FROM FACTURA WHERE FACTURA.ID_CLI = CLIENTE.ID_CLI AND TIPO_MOV_FACT='SALIDA');
GO 

EXEC SP_CLIENTES_UNICOS
